version: "3"

services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    cpus: "0.5"
    volumes:
      - "/docker/appdata/firefox:/config:rw"
    mem_reservation: "2G"
    mem_limit: "3G"
    networks:
      custom-network:
        ipv4_address: 172.16.239.2 # Assign a specific IP address in the custom network

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
